export let cardArray = [ { img: './image/pizza-bbq.png',
            title: 'Чизбургер барбекю',
            description: 'Соус коктейль, фарш из отборной говядины, маринованные огурцы, спелые томаты, сыр моцарелла, сыр чеддер, соус барбекю, хрустящий лук',
            price: '560',
            discount: '888',
            label: 'd-lg-none'},

            { img: './image/pizza-suprim.png',
              title: 'Суприм',
              description: 'Соус томатный, сыр моцарелла, колбаса пепперони, ветчина, лук, сладкий перец, грибной микс, свинина, говядина, оливки черные',
              price: '690',
              discount: '',
              label: 'card__label-new'},

            { img: './image/burger.png',
              title: 'Бургер «Два сыра»',
              description: 'Ароматная котлета из мраморной говядины с сыром чеддер и моцарелла, хрустящим луком, маринованными корнишонами, свежими томатами, соусом коктейль и барбекю в мягкой пшеничной булочке. Картофель и соус приобретается отдельно',
              price: '180',
              discount: '',
              label: 'card__label-new'},

            { img: './image/sushi.png',
              title: 'Унаги',
              description: 'Угорь',
              price: '190',
              discount: '200',
              label: 'card__label-new'},

            { img: './image/sushi-2.png',
              title: 'Умэ',
              description: 'Лосось, угорь, сыр «Филадельфия», авокадо',
              price: '120',
              discount: '',
              label: 'card__label-new'}
]
